### ISSUE TITLE
JCU Heading Colours for themes component

### ISSUE THREAD

**Issue by melissalv** [jcu/cookbook#10]
Header graduations based on JCU colour gradients, orange, blue, red and green, provided by Cam >
[Microsite Template .pdf](https://github.com/jcu/web-framework/files/203848/Microsite.Template.pdf)

**Comment by davidjb** [comment]
@melissalv, I've added these colours into the Themes component at https://web.jcu.io/jcu/themes/ -- you'll need to do a sync on your repository (eg Github Desktop client) to pull down the latest changes to the built CSS.  The CSS changes might require you to clear your browser's cache.
