### ISSUE TITLE
Add transitions to single-page examples

### ISSUE THREAD

**Issue by davidjb** [jcu/cookbook#11]
An example page like: http://pages.gitlab.io/ has CSS transitions which get applied from the application of the `.is-visible` class to `.js-step` elements. We should do something similar for our single page examples and make them really pop.

Source code: 
https://gitlab.com/pages/pages.gitlab.io/blob/master/source/javascripts/application.js.coffee

**Comment by trinerosep** [comment]
Would like to try using this one, looks great!

**Comment by davidjb** [comment]
Done for the example @ https://web.jcu.io/examples/jcu-landing/.  Animations could consist of anything supported by Animate.css (https://daneden.github.io/animate.css/)

Getting this onto a page or app requires additional libraries not present within the main Web Framework (and some JavaScript to wire it up) but it's pretty light-weight and demonstrated in https://github.com/jcu/web-framework/tree/master/docs/examples/jcu-landing, `js/landing.js` and `index.html`.
