### ISSUE TITLE
Allow switching OFF the display of <a> hrefs when formatting for printing

### ISSUE THREAD

**Issue by DanielBaird** [jcu/cookbook#17]
Our print stylesheets add ` (attr[href])` content `::after` `<a>` tags.  This is usually fine, except sometimes there's the same link multiple times over (e.g. you might link to the same place from the heading, image and "more" button in an info box)... so we need to have a way to disable the link-writing-out behaviour.

**Comment by davidjb** [comment]
Closing in lieu of simplifying the library down to being a theming layer rather than a complete suite of JCU-specific components.
