### ISSUE TITLE
Branch jcu-code-review

### ISSUE THREAD

**Issue by chema64** [jcu/cookbook#23]
The Clean & migrate extra JCU code to Bootstrap v4-b2 commit from jcu-code-review (3116551fa74064b79c98381a1786702d672a527f) has been successfully cherry picked into the v2-dev branch (613a38536cd61ccedb55516a361645161022112e).  Should the jcu-code-review branch be deleted?, or is it going to be used for other future tasks?

**Comment by davidjb** [comment]
Branch deleted and cleaned up.
