### ISSUE TITLE
Theme colours needs better contrast for accessibilty

### ISSUE THREAD

**Issue by DanielBaird** [jcu/cookbook#25]
Trine Paerata reported via Slack that:
>> the 'text-muted' class that is used on summary cards (byline header) comes up as low contrast  for size with a 4.3 ratio (it's just under as ratio needs to be at least 4.5)

..so we should tweak the grey to be a bit darker.

**Comment by davidjb** [comment]
So effectively all the colour utils currently in use by the Web Framework need adjustment, but the same is true of core Bootstrap as well (eg https://getbootstrap.com/docs/4.1/utilities/colors/).  Reported already at https://github.com/twbs/bootstrap/issues/25126 so we'll follow that in the meantime and adjust the colours when/if Web Framework v2 is released.

**Comment by davidjb** [comment]
Closing this out as CookBook v2 has addressed this specific issue in its releases, ensuring that the v2 (Bootstrap v4) builds are being tested for accessibility in common situations in our current documentation. The explanation at https://github.com/jcu/cookbook#accessibility covers other and non-standard ways in which classes can be mixed and matched, and how it is ultimately up to the end designer to ensure accessibility.
