### ISSUE TITLE
Update for Bootstrap 5

### ISSUE THREAD

**Issue by davidjb** [jcu/cookbook#34]
Build steps in package.json (originally copied from Bootstrap v4 and customised to suit our needs), all package dependencies and SCSS should be updated for Bootstrap 5 and a new major version of Cookbook should be released to coincide with the breaking changes that v5 brings.

Other considerations:

* Our release notes / change log should include references to the v5 Migration docs (https://getbootstrap.com/docs/5.0/migration/)
* The change to Dart Sass means that the ways in which font libraries are included and used can now be cleaned up as `@use` is available rather than `@import`.  See https://github.com/fontsource/fontsource/issues/130

**Comment by TimEnglart** [comment]
Bootstrap 5.1 implemented and deployed in commit: d9989e27c73f6fea598a45e96243a11c7bf3ce4c
