### ISSUE TITLE
Upgrade to Yarn 2+ or switch to NPM

### ISSUE THREAD

**Issue by davidjb** [jcu/cookbook#36]
With yarn v1 moving towards EOL, we need to investigate an upgrade to Yarn 2.  The build scripts come from the core of Bootstrap, which centres on using `npm` as its package manager, so if Yarn 2+ represents a maintenance burden, it might be easier for us to switch to using `npm` for ease of working with upstream.

**Comment by TimEnglart** [comment]
Upgraded to yarn 2 on commit: dfeea7d2101de9a048945563c9a83bfe57a0230f

**Comment by TimEnglart** [comment]
Upgraded to yarn 2 in commit: dfeea7d2101de9a048945563c9a83bfe57a0230f

**Comment by TimEnglart** [comment]
Upgraded to yarn 2 in commit: dfeea7d2101de9a048945563c9a83bfe57a0230f

Note: Still currently uses node_modules
