### ISSUE TITLE
Test CDN URLs & npm package after upload during CD process

### ISSUE THREAD

**Issue by davidjb** [jcu/cookbook#42]
Add tests for loading the key URLs on the given CDN (`css/cookbook.min.css`, `js/bootstrap.min.js` and `img/favicon.ico`) after the deployment process to ensure the public URLs are all wired up okay.

Also, a test `npm install @jcu/cookbook@[RELEASE_VERISON`` would ensure that npm's made the package available okay as well.

**Comment by TimEnglart** [comment]
Resolved in commit: 9a50a0a
