### ISSUE TITLE
Make master auto npm deploy opt-in

### ISSUE THREAD

**Issue by davidjb** [jcu/cookbook#43]
We were chatting yesterday and on balance, automatically deploying each commit will result in a lot of extraneous packages on npm, some of which might have very little or no significant changes and someone needing the bleeding edge in a package is probably able to use `yarn link` if they really need to work on both CookBook and their project simultaneously. This is much faster too - and which is better for iterating on untested/in-development work.  

So, let’s make npm publication opt-in via a flag in the commit message (but only for the master branch; tags should always auto publish).

**Comment by TimEnglart** [comment]
Resolved in commit: 516d83f

As stated in commit message put `[npm publish]` somewhere in your commit message for the master pre-release workflow to publish to npm (still publish's to CDN)
